# Generated by Django 5.1.3 on 2024-11-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bank_number',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
