# Generated by Django 5.1.3 on 2024-12-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_product_bank_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_create_product', 'Can create product'), ('can_update_product', 'Can update product'), ('can_delete_product', 'Can delete product'), ('can_view_product', 'Can view product')]},
        ),
        migrations.AlterField(
            model_name='product',
            name='bank_number',
            field=models.BinaryField(),
        ),
    ]
