# Generated by Django 5.1.3 on 2024-12-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_encryptionkey_alter_product_encryption_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncryptionKey',
        ),
    ]
