# Generated by Django 5.1.3 on 2024-12-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_encryptionkey_alter_product_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncryptionKey',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_create_product', 'Can create product'), ('can_update_product', 'Can update product'), ('can_delete_product', 'Can delete product'), ('can_view_product', 'Can view product'), ('can_view_own_products', 'Can view own products'), ('can_view_all_products', 'Can view all products')]},
        ),
    ]
