# Generated by Django 5.1.3 on 2024-12-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_delete_encryptionkey_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(max_length=50, unique=True)),
                ('encrypted_key', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_create_product', 'Can create product'), ('can_update_product', 'Can update product'), ('can_delete_product', 'Can delete product'), ('can_view_product', 'Can view product'), ('can_view_own_products', 'Can view own products'), ('can_view_all_products', 'Can view all products'), ('can_view_product_keys', 'Can view and update encryption keys')]},
        ),
    ]
